export const transitionSentences = [
  "Compiling visual momentum.",
  "Routing through crafted intent.",
  "Structure before spectacle.",
  "Precision is loading.",
  "Designing with technical gravity.",
  "Every frame has a purpose.",
  "Signal over noise.",
  "Interface integrity in motion.",
  "Performance meets editorial rhythm.",
  "Pushing pixels with discipline.",
  "Calibrating the next view.",
  "Depth, clarity, velocity.",
  "Built to feel inevitable.",
  "Carefully engineered transitions.",
  "A cleaner state is arriving.",
  "Flowing into the next chapter.",
  "Motion with measurable intent.",
  "Shaping interaction with precision.",
  "The system is in sync.",
  "Refining the visual signal.",
  "Navigation with narrative weight.",
  "Architecture in active motion.",
  "Timings tuned for clarity.",
  "Switching context seamlessly.",
  "Detail-first interaction design.",
  "Quietly accelerating experience.",
  "Composed movement, clean delivery.",
  "From one state to the next.",
  "Coordinating form and function.",
  "Transitioning with intention.",
];

export const routeTransitionConfig = {
  accentColor: "#ff5733",
  sentences: transitionSentences,
};
